<?php

namespace Tests;

use App\About;
use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{

    use CreatesApplication;

    public function setUp(): void

    {

        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }


    protected function callBeforeApplicationDestroyedCallbacks()
    {

         
        parent::callBeforeApplicationDestroyedCallbacks();
    }

    protected function tearDown(): void
    {

        $tables = array(
            'about',
            'blog_categorys',
            'blog_categorys_access',
            'blog_posts',
            'blog_posts_comments',
            'blog_posts_comments_comments',
            'elfinder_files',
            'multiselect',
            'pages',
            'proj_categorys',
            'proj_invoices',
            'proj_notifys',
            'proj_portfolio',
            'proj_portfolio_categorys',
            'proj_project_comments',
            'proj_project_comments_comments',
            'proj_project_invoices',
            'proj_project_offers',
            'proj_project_offers_comments',
            'proj_project_users',
            'proj_projects',
            'proj_reviews',
            'proj_statuses',
            'proj_users',
            'proj_users_categorys',


        );
        if (count($tables)) {
            foreach ($tables as $table) {
                DB::table($table)->delete();
            }
        }


        parent::tearDown();
    }

}
